### ISSUE TITLE
Wrong working directory when building on TeamCity

### ISSUE THREAD

**Issue by eggapauli** [ParticularLabs/GitVersion#396]
When we run GitVersion 3.0.0-Beta1 on TeamCity, it clones parts of the repository to "<basePath>\_dynamicrepository" using [GitPreparer.Prepare](https://github.com/ParticularLabs/GitVersion/blob/f7b096f4585709be43b5d13a2de9f3cd44b7e97e/GitVersionExe/GitPreparer.cs#L23). When finished, this method returns the path to the prepared repository (i.e. "\<basePath\>\\_dynamicrepository\\.git") and [sets "\<basePath\>\\_dynamicrepository" as working directory](https://github.com/ParticularLabs/GitVersion/blob/f7b096f4585709be43b5d13a2de9f3cd44b7e97e/GitVersionExe/Program.cs#L85).  
Now when the command line switch `/exec` is set, GitVersion executes the exe in the dynamic repository instead of the original repository as we would have expected. That then destroys some relative paths we are working with in the supplied exe file.  
Can you confirm this or are we doing something wrong here?

**Comment by JakeGinnivan** [comment]
Thoughts @GeertvanHorrik @gep13

**Comment by GeertvanHorrik** [comment]
I think we need to split the directories internally for WorkingDirectory (source) and the GitDirectory. They might not be in the same place.

**Comment by JakeGinnivan** [comment]
Makes sense to me. Need to pull the execution stuff out of Program.cs so we can write some tests around it too. Will see if I can tackle over the weekend unless someone wants to jump in and do it first :)

**Comment by GeertvanHorrik** [comment]
Happy to help, but I really need a few features finished this week, too much PR / open source last weekend ;-)

Maybe later this week, but I might forget.

**Comment by gep13** [comment]
Makes sense to me :+1:

**Comment by eggapauli** [comment]
We also recognized that the variables are wrong when using _dynamicrepository. It is calculated in the dynamic repository instead of the original one. Is it the same cause you think?

**Comment by GeertvanHorrik** [comment]
The best way to explain a problem is a failing unit test. Is that something you can create? Then we know exactly what issue to solve ;-)

**Comment by eggapauli** [comment]
I can't at the moment, because `GitPreparer.Prepare` directly uses `Repository.Clone` to create the `_dynamicrepository`, so I can't mock it, but maybe a function test is possible.

**Comment by eggapauli** [comment]
You can see the effect simply using the following powershell line

    gitversion /url c:/users/egger/workspace/WeinCad.Net /exec "powershell" /execargs "-Command pwd"

where WeinCad.Net is a git repository. The output of the command is

    Path
    ----
    C:\Users\egger\Downloads\WeinCAD.NET\_dynamicrepository

so you can see that execed command is being run in an environment with working directory set to the __dynamicdirectory__

**Comment by eggapauli** [comment]
To demonstrate that `GitVersion` calculates the variables based on the `_dynamicrepository`, run the following commands:

    # create local repo
    mkdir local
    cd .\local
    git init
    git commit --allow-empty -m "Commit 1"

    # create remote repo
    git clone . ..\remote 
    cd ..\remote
    git commit --allow-empty -m "Commit 2" # someone pushes to the remote repo

    # check versions in local repo
    cd ..\local
    gitversion /exec "powershell" /execargs '-Command echo $env:GitVersion_FullSemVer' # 0.1.0+0
    gitversion /url ..\remote /exec "powershell" /execargs '-Command echo $env:GitVersion_FullSemVer' # 0.1.0+1
    cd ..
    rm -Force -Recurse local,remote
    
Both `GitVersion` commands should produce the same output.

**Comment by eggapauli** [comment]
I used GitVersion 3.0.0-Beta1 for both tests.

**Comment by GeertvanHorrik** [comment]
I think @JakeGinnivan already created a PR for this (see https://github.com/ParticularLabs/GitVersion/pull/399), but it's not put into Beta1 yet. I have reviewed the code, but just didn't find time to really try it out.

**Comment by eggapauli** [comment]
I thought the PR is only to create the repository in a tmp directory and to not delete it every time. Did I overlook something?

**Comment by GeertvanHorrik** [comment]
You are absolutely right, I must have been sleeping while I posted that. Sorry about the confusion.

**Comment by JakeGinnivan** [comment]
Actually, I think I fixed it here in that PR - https://github.com/JakeGinnivan/GitVersion/commit/01d4f849a3f401823f04e8327fdd2a7f985c4f02#diff-cdf777fc03b2d4c69c5026eaafd6c2f8R60

Most places that were looking at the gitDirectory now look at target path

**Comment by eggapauli** [comment]
I just tried your PR.
It fixes the first issue (i.e. it executes the `exec` with the correct working directory), but doesn't fix the second issue (it still computes version variables of the dynamic repo, not of the real one).

**Comment by GeertvanHorrik** [comment]
I think how teamcity responds to this is a bit out of scope because I want to be able to determine the version of any repository at any time. You can use the /c parameter. I use it like this on Continua CI:

```
/url %RepositoryUrl% /b %RepositoryBranchName% /c %RepositoryCommitId% /output buildserver
```

**Comment by eggapauli** [comment]
Ahh I see, `/c` hasn't been documented so far, that's why I couldn't find it.

**Comment by JakeGinnivan** [comment]
@eggapauli correct, it will be in 3.0.0 stable.

**Comment by JakeGinnivan** [comment]
Or Beta2. unsure which I should release :P

**Comment by eggapauli** [comment]
Perfect, thanks. Will it check out the same commit as the local repo by default?

**Comment by JakeGinnivan** [comment]
You have to use `/c <sha>` to ensure the commit. By default it will use the branch specified on the command line

**Comment by eggapauli** [comment]
Ok I see. So without `/c` it could be possible to get the wrong version, if the dynamic repo is ahead of the local one, right?

**Comment by JakeGinnivan** [comment]
Yep

**Comment by eggapauli** [comment]
Ok, thanks.
